"use client"
import { useEffect, useState } from "react";
import Pagination from "../pagination/Pagination";
import { useTranslation } from "react-i18next";



const experienceObj = [{
    "nameCorp":"HCL Mexico",
    "location":"Guadalajara Jalisco",
    "dates":"September 2017 to December 2023",
    "positionName":"Front End Developer.",
    "info": "I worked as a contractor for USAA in the corporate services department, where we developed and maintained applications in React to enhance productivity.\n\nIn terms of front-end applications, we utilized React and Redux Toolkit. One notable project involved  reating a system to locate work areas based on codes generated by Archibus. Additionally, we developed an inventory management system, which boasted over 5,000 users, and another system for orthopedic management teams. My responsibilities included supporting development, troubleshooting, conducting technology research and supporting releases through health and smoke testing.\n\n On the backend, I focused on maintaining a REST API that integrated information from the Archibus system across various departments. Using Node.js, I developed new endpoints,maintained existing ones, assisted with troubleshooting, conducted technology research, and provided support for production releases.\n\nI was also involved in several migrations, including migrating REST APIs from Hibernate to Spring Boot, transitioning test cases from ReadyAPI to Postman, and migrating backend projects from Openshift 3 to 4, as well as migrating front-end projects from Openshift 3 to AWS.\n\nThroughout these projects, I worked in an agile environment based on Scrum, participating in the complete cycle, including product backlog management, sprint planning, implementation, review, and retrospective, with 2-week sprints"
},
{
    "nameCorp":"Korsoftocorp",
    "location":"Hermosillo sonora",
    "dates":"October 2013 to August 2017.",
    "positionName":"Front End Developer.",
    "info": "I supported the front-end team by resolving technical and business problems, ensuring smooth releases of applications on AppStore and Play Store, and ensuring compliance with platform requirements. We successfully launched three hybrid apps, including one in Córdoba and two in React Native, along with maintaining a fourth built in Appcelerator.\n\nOne of our projects involved developing an app for managing soccer football coaches, facilitating team control, game scheduling, player organization, and parent communication. Initially developed in Córdoba using Ionic and PHP for the backend, we utilized REST APIs hosted on AWS cloud servers. Our toolset included Cordova, Ionic, GitHub, Postman, and AppStore/Play Store for deployment.\n\n Another significant project was an app for managing maintenance activities in a college setting. This app enabled tracking of tasks across all floors, scheduling new activities, assigning duties, and monitoring activity status. We developed an admin portal in PHP and an iOS app for workers to view and update their activities. Technologies used included React Native, Redux, AWS, GitHub, Postman, and AppStore/Play Store for deployment.\n\nThroughout these projects, we operated in an Agile environment based on Scrum, actively participating in the complete development cycle, including product backlog management, sprint planning, implementation, review, and retrospective, with 2-week sprints."
},
{
    "nameCorp":" Internet Brands.",
    "location":"Guadalajara Jalisco",
    "dates":"February 2012 to October 2013.",
    "positionName":"Front End Developer.",
    "info": "As a contractor for Internet Brands, I contributed to the content team as a front-end developer, where I played a pivotal role in developing and maintaining the www.carsdirect.com page. This involved managing the content management module using PHP Igniter, and implementing HTML and jQuery for the front end. My responsibilities encompassed both content management and visualization, ensuring a seamless user experience.\n\n Additionally, I lead the development of an image viewer for www.davesgarden.com/showcase, collaborating with two team members to ensure its successful implementation. I conducted code reviews, addressed various technical challenges, and explored the integration of new technologies such as Bootstrap, Angular, and  Query Mobile.\n\n Moreover, I actively maintained a content system, allowing writers to contribute articles for display on various platforms. This involved implementing features such as word count calculations to determine fair compensation for writers. I was responsible for both HTML and JavaScript aspects of the system, ensuring smooth interaction with the backend.\n\n Throughout these projects, I operated in an agile environment based on Scrum, participating in the complete development cycle, including product backlog management, sprint planning, implementation, review, and retrospective, with 2-week sprints."
},
{
    "nameCorp":"quepasa.com",
    "location":"Hermosillo sonora",
    "dates":"October 2007 to January 2012.",
    "positionName":"Front End Developer.",
    "info": "At Quepasa.com, a social networking platform, I served as a front-end developer, eventually progressing to a team leader role four years into my tenure. My responsibilities included maintaining the site, which was developed using PHP for the backend and JavaScript plus HTML for the front end.\n\n Throughout my time at Quepasa.com, I navigated through various phases of technologies. Initially, we utilized MVC architecture before transitioning to REST API. I worked extensively with pure JavaScript and later transitioned to jQuery for enhanced functionality. Additionally, I managed connections with third-party applications, ensuring seamless integration and user experience.\n\n In addition to technical duties, I played a key role in maintaining usability standards, conducting troubleshooting and testing, and researching new technologies to improve platform performance. I also took charge of implementing and reviewing web analytics, particularly utilizing Google Analytics to track user engagement and inform decision-making processes.\n\n Regarding our working methodology, we initially followed a waterfall model before transitioning to an agile environment in 2010. In this agile setup, I actively participated in the complete development cycle, including product backlog management, sprint planning, implementation, review, and retrospective, with 2-week sprint."
}
];

const paginationObj = {
    currentPage: 1,
    total: experienceObj.length
};

export default function Experience() {
    const { i18n, t } = useTranslation();
    const [currentObj,setCurrentObj] = useState(experienceObj[0]);
    const [totalPages] = useState(experienceObj.length);
    const [currentPage, setCurrentPage] = useState<number>(1);
    const [pagination, setPagination] = useState(paginationObj);

    function nextPage(){
        const current = currentPage +1;
        setCurrentPage(current);
    }

    function prevPage(){
        const current = currentPage -1;
        setCurrentPage(current);
        
    }

   useEffect(()=>{
      const current = currentPage-1;
      setCurrentObj(experienceObj[current]);
      setPagination(
            {...pagination,
            currentPage:currentPage
        }
        ); 
    },[currentPage]);

    return (
      <>
      <div className="p-5 bg-subHeader rounded border-borderColor m-2 min-h-20 exp-step">
        <h1 className="float-left text-slate-100 inline-block text-2xl sm:text-3xl font-extrabold tracking-tight">{t("exp")}</h1>
        {totalPages>1?( <Pagination onNext={nextPage} onPrev={prevPage} pagination={pagination} />):("")}
      </div>
        <div className="experienceContent p-10 bg-module p-5 rounded border-borderColor border-2 m-2">
            <>
                <div className="experienceData m-1">
                    <h1 className="text-2xl font-bold dark:text-white">{currentObj.nameCorp}, <small className="ms-2 font-semibold text-gray-500 dark:text-gray-400">{currentObj.location}</small> </h1>
                    <h2 className="ms-2 font-semibold text-gray-500 dark:text-gray-400">{currentObj.dates}</h2>
                    <h2 className="ms-2 font-semibold text-gray-500 dark:text-gray-400">{currentObj.positionName}</h2>
                </div>
                <p className="experienceInfo m-5 whitespace-break-spaces mb-3">
                    {currentObj.info}
                </p>
            </>            
            {totalPages>1?( <Pagination onNext={nextPage} onPrev={prevPage} pagination={pagination} />):("")}       
        </div>
        
      </>
    );
  }
  